//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_pagamento
    {
        public int pagamento_id { get; set; }
        public int pagamento_aluno_id { get; set; }
        public Nullable<System.DateTime> pagamento_vencimento { get; set; }
        public string pagamento_modalidade { get; set; }
        public Nullable<float> pagamento_valor { get; set; }
        public string pagamento_obs { get; set; }
        public string pagamento_status { get; set; }
        public string patamento_formapgt { get; set; }
        public Nullable<System.DateTime> pagamento_data { get; set; }
        public Nullable<float> pagamento_valorpgt { get; set; }
        public string pagamento_ncheque { get; set; }
        public string pagamento_nbanco { get; set; }
        public string pagamento_nagencia { get; set; }
        public string pagamento_modalidadesAdicionais { get; set; }
        public string pagamento_tipo { get; set; }
    
        public virtual gerjfd_aluno gerjfd_aluno { get; set; }
    }
}
