//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_aluno
    {
        public int aluno_id { get; set; }
        public string aluno_nome { get; set; }
        public string aluno_endereco { get; set; }
        public string aluno_numero { get; set; }
        public string aluno_bairro { get; set; }
        public string aluno_cidade { get; set; }
        public string aluno_rg { get; set; }
        public string aluno_cpf { get; set; }
        public string aluno_telResidencial { get; set; }
        public string aluno_telComercial { get; set; }
        public string aluno_celular { get; set; }
        public System.DateTime aluno_dataNascimento { get; set; }
        public string aluno_email { get; set; }
        public string aluno_nomeMae { get; set; }
        public string aluno_telMae { get; set; }
        public string aluno_nomePai { get; set; }
        public string aluno_telPai { get; set; }
        public string aluno_peso { get; set; }
        public string aluno_altura { get; set; }
        public string aluno_pressaoArterial { get; set; }
        public string aluno_modalidadePraticada { get; set; }
        public string aluno_problemaSaude { get; set; }
        public string aluno_cirurgia { get; set; }
        public string aluno_alergiaMedicamento { get; set; }
        public string aluno_parentesco { get; set; }
        public System.DateTime aluno_dataInicio { get; set; }
        public string aluno_diaVencimento { get; set; }
        public Nullable<double> aluno_valor { get; set; }
        public string aluno_digital1 { get; set; }
        public string aluno_digital2 { get; set; }
        public string aluno_modalidade { get; set; }
        public string aluno_modalidadeAdicionais { get; set; }
        public string aluno_praticouModalidade { get; set; }
        public string aluno_fumante { get; set; }
        public string aluno_doencaCardiovascular { get; set; }
    }
}
