//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_view_dev
    {
        public int aluno_id { get; set; }
        public string aluno_nome { get; set; }
        public int pagamento_id { get; set; }
        public Nullable<System.DateTime> pagamento_vencimento { get; set; }
        public Nullable<float> pagamento_valor { get; set; }
        public Nullable<System.DateTime> pagamento_data { get; set; }
        public Nullable<float> pagamento_valorpgt { get; set; }
        public string pagamento_modalidade { get; set; }
        public string pagamento_modalidadesAdicionais { get; set; }
    }
}
