//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_frequencia
    {
        public int frequencia_id { get; set; }
        public Nullable<int> frequencia_aluno_id { get; set; }
        public Nullable<int> frequencia_id_agenda { get; set; }
        public Nullable<System.DateTime> frequencia_data { get; set; }
    
        public virtual gerjfd_aluno gerjfd_aluno { get; set; }
    }
}
