//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_agenda
    {
        public int agenda_id { get; set; }
        public Nullable<int> agenda_id_modalidade { get; set; }
        public string agenda_dia_semana { get; set; }
        public string agenda_horario { get; set; }
        public string agenda_ativa { get; set; }
    
        public virtual gerjfd_modalidade gerjfd_modalidade { get; set; }
    }
}
