//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoZumba
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerjfd_modalidade
    {
        public int modalidade_id { get; set; }
        public string modalidade_nome { get; set; }
        public Nullable<float> modalidade_vlrp { get; set; }
        public Nullable<float> modalidade_vlra { get; set; }
    }
}
